# Generated by Django 4.2.23 on 2025-08-15 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_customers_alter_product_description_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customers',
            new_name='Customer',
        ),
    ]
